# Generated by Django 5.1.7 on 2026-05-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='time_slot',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='is_hourly',
            field=models.BooleanField(default=False, verbose_name='Hodinové rezervace'),
        ),
    ]
